// <auto-generated />
using System;
using CadifaApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CadifaApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260626124511_AddNotificadoEmToCadifaAlteracoes")]
    partial class AddNotificadoEmToCadifaAlteracoes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CadifaApi.Models.Cadifa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Data")
                        .HasColumnType("text")
                        .HasColumnName("data");

                    b.Property<DateTime>("DataColeta")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_coleta");

                    b.Property<string>("Empresa")
                        .HasColumnType("text")
                        .HasColumnName("empresa");

                    b.Property<string>("Hash")
                        .HasColumnType("text")
                        .HasColumnName("hash");

                    b.Property<string>("Insumo")
                        .HasColumnType("text")
                        .HasColumnName("insumo");

                    b.Property<string>("Processo")
                        .HasColumnType("text")
                        .HasColumnName("processo");

                    b.Property<string>("Revisao")
                        .HasColumnType("text")
                        .HasColumnName("revisao");

                    b.HasKey("Id");

                    b.ToTable("cadifa", (string)null);
                });

            modelBuilder.Entity("CadifaApi.Models.CadifaAlteracao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Data")
                        .HasColumnType("text")
                        .HasColumnName("data");

                    b.Property<DateTime>("DataDeteccao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_deteccao");

                    b.Property<string>("Empresa")
                        .HasColumnType("text")
                        .HasColumnName("empresa");

                    b.Property<string>("Hash")
                        .HasColumnType("text")
                        .HasColumnName("hash");

                    b.Property<string>("Insumo")
                        .HasColumnType("text")
                        .HasColumnName("insumo");

                    b.Property<DateTime?>("NotificadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Processo")
                        .HasColumnType("text")
                        .HasColumnName("processo");

                    b.Property<string>("Revisao")
                        .HasColumnType("text")
                        .HasColumnName("revisao");

                    b.Property<string>("Tipo")
                        .HasColumnType("text")
                        .HasColumnName("tipo");

                    b.HasKey("Id");

                    b.ToTable("cadifa_alteracoes", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
